Vagrant.configure("2") do |config|
  # General Vagrant VM configuration.
  config.vm.box = "geerlingguy/centos7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
	v.cpus = 1
    v.memory = 256
    v.linked_clone = true
  end

  # Node#1
  config.vm.define "single-node" do |node|
    node.vm.hostname = "single-node.test"
    node.vm.network :private_network, ip: "192.168.60.100"
  end
end

