VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
	config.vm.box = "geerlingguy/centos7"

	config.vm.provider :virtualbox do |vbox|
		vbox.cpus = 1
		vbox.memory = 256
		vbox.linked_clone = true
	end

	# Apache webserver
	config.vm.define "apache-webserver" do |node|
		node.vm.hostname = "apache-webserver.test"
		
		# Network + forwarded port
		node.vm.network :private_network, ip: "192.168.60.101"
		node.vm.network :forwarded_port, guest: 80, host: 8081
		
		# Provisioning
		node.vm.provision :shell, name: "update", path: "update.sh"
		node.vm.provision :shell, name: "apache", path: "setup-apache.sh"
	
	end
	
end

