# Vagrantfile for NodeA, on Host#1

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "geerlingguy/centos7"

	config.vm.provider :virtualbox do |v|
		v.cpus = 1
		v.memory = 256
		v.linked_clone = true
	end

	# Node#1
	config.vm.define "nodeA" do |node|
		node.vm.hostname = "nodeA.test"
		
		# DHCP
		node.vm.network "public_network"
					
	end
	
end
