# Vagrantfile for NodeB, on Host#2

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "geerlingguy/centos7"

	config.vm.provider :virtualbox do |v|
		v.cpus = 1
		v.memory = 256
		v.linked_clone = true
	end

	# Node#2
	config.vm.define "nodeB" do |node|
		node.vm.hostname = "nodeB.test"

		# DHCP
		node.vm.network "public_network"

	end
	
end
