# -*- mode: ruby -*-
# vi: set ft=ruby :

# Pre-requisite:
# SSH keypair generated using ssh-keygen.

# After provision: test the 'control' node:
# vagrant ssh control
# python --version
# pyhon3 --version
# ansible --version

VAGRANTFILE_API_VERSION = "2"
SSH_PRIVATE_KEY_PATH = "c:/Data/dev/_keys/vagrant"
SSH_PUBLIC_KEY_PATH = "c:/Data/dev/_keys/vagrant.pub"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "geerlingguy/centos7"

	config.vm.provider :virtualbox do |vbox|
		vbox.cpus = 1
		vbox.memory = 1024
		vbox.linked_clone = true
	end

	# Inject SSH public keys
	config.ssh.insert_key = true

	# Control Node
	config.vm.define "control" do |control|
		control.vm.hostname = "control.test"
		control.vm.network :private_network, ip: "192.168.100.100"

		# Inject SSH public and private  key
		control.vm.provision "copy-ssh-public-key", type: "file", source: SSH_PUBLIC_KEY_PATH, destination: "~/.ssh/vagrant.pub"
		control.vm.provision "copy-ssh-private-key", type: "file", source: SSH_PRIVATE_KEY_PATH, destination: "~/.ssh/vagrant"
		control.vm.provision :shell, name: "private-key-privileges", privileged: false, path: "vagrantscripts/private-key.sh"
		
		# Install Ansible
		control.vm.provision :shell, name: "install-python3", path: "vagrantscripts/python3.sh"
		control.vm.provision :shell, name: "install-ansible", path: "vagrantscripts/ansible.sh"
	end

end

