# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "geerlingguy/centos7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
	v.cpus = 1
    v.memory = 256
    v.linked_clone = true
  end

  # Node#1
  config.vm.define "node1" do |node|
    node.vm.hostname = "node1.test"
    node.vm.network :private_network, ip: "192.168.60.1"
  end

  # Node#2
  config.vm.define "node2" do |node|
    node.vm.hostname = "node2.test"
    node.vm.network :private_network, ip: "192.168.60.2"
  end

  # Node#3
  config.vm.define "node3" do |node|
    node.vm.hostname = "node3.test"
    node.vm.network :private_network, ip: "192.168.60.3"
  end

  # Node#4
  config.vm.define "node4" do |node|
    node.vm.hostname = "node4.test"
    node.vm.network :private_network, ip: "192.168.60.4"
  end

 end
 