# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/centos7"

  config.vm.provider :virtualbox do |vbox|
	vbox.cpus = 1
    vbox.memory = 1024
    vbox.linked_clone = true
  end

  # Node#1
  config.vm.define "node1" do |node|
    node.vm.hostname = "node1.test"
    node.vm.network :private_network, ip: "192.168.100.101"
  end

  # Node#2
  config.vm.define "node2" do |node|
    node.vm.hostname = "node2.test"
    node.vm.network :private_network, ip: "192.168.100.102"
  end

  # Node#3
  config.vm.define "node3" do |node|
    node.vm.hostname = "node3.test"
    node.vm.network :private_network, ip: "192.168.100.103"
  end

  # Node#4
  config.vm.define "node4" do |node|
    node.vm.hostname = "node4.test"
    node.vm.network :private_network, ip: "192.168.100.104"
  end

 end
 