# -*- mode: ruby -*-
# vi: set ft=ruby :

# Ansible control node and slave nodes on Host#1.

# Pre-requisite:
# SSH keypair generated using ssh-keygen. Same SSH keypair available on each host.

# The 'rsync' method is used for synced folders. (ansible project folders)
# This means that after changes within those folders on the host, a folder sync has to be triggered:
# vagrant rsync

# After the provisioning finishes, login to 'control' node:
# vagrant ssh control

# Check if ansible is properly installed:
# ansible --version

# Before start using ansible, add the private key to the keyring. 
# This is needed to be able to ssh to the other nodes from the control node.
# eval $(ssh-agent -s)
# ssh-add ~/.ssh/vagrant

# Test ansible by pinging the other nodes
# cd /ansible/ad-hoc
# ansible -m ping all

VAGRANTFILE_API_VERSION = "2"
SSH_PRIVATE_KEY_PATH = "R:/_keys/vagrant3"
SSH_PUBLIC_KEY_PATH = "R:/_keys/vagrant3.pub"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "geerlingguy/centos7"

	config.vm.provider :virtualbox do |vbox|
		vbox.cpus = 1
		vbox.memory = 1024
		vbox.linked_clone = true
	end

	# Inject SSH public keys
	config.ssh.insert_key = true

	config.vm.provision "copy-ssh-public-key", type: "file", source: SSH_PUBLIC_KEY_PATH, destination: "~/.ssh/vagrant.pub"
	config.vm.provision "attach-ssh-key", type: "shell", privileged: false, inline: <<-SHELL
		cat ~/.ssh/vagrant.pub >> ~/.ssh/authorized_keys
	SHELL

	# Control Node
	config.vm.define "control1" do |control|
		control.vm.hostname = "control1.test"
		control.vm.network "public_network"

		# Inject SSH private  key
		control.vm.provision "copy-ssh-private-key", type: "file", source: SSH_PRIVATE_KEY_PATH, destination: "~/.ssh/vagrant"
		control.vm.provision :shell, name: "private-key-privileges", privileged: false, path: "../vagrantscripts/private-key.sh"
		
		# Install Ansible
		control.vm.provision :shell, name: "install-python3", path: "../vagrantscripts/python3.sh"
		control.vm.provision :shell, name: "install-ansible", path: "../vagrantscripts/ansible.sh"
		
		# Add synced folders for ansible projects
		control.vm.synced_folder "../ansible", "/ansible", type: "rsync"

	end

	# Node#1
	config.vm.define "node1" do |node|
		node.vm.hostname = "node1.test"
		node.vm.network "public_network"
	end

	# Node#2
	config.vm.define "node2" do |node|
		node.vm.hostname = "node2.test"
		node.vm.network "public_network"
	end

	# Node#3
	config.vm.define "node3" do |node|
		node.vm.hostname = "node3.test"
		node.vm.network "public_network"
	end

	# Node#4
	config.vm.define "node4" do |node|
		node.vm.hostname = "node4.test"
		node.vm.network "public_network"
	end

end

